### ISSUE TITLE
Can't find framework headers with Xcode 7.3

### ISSUE THREAD

**Issue by sirnacnud** [clawoo/Disk-Inventory-X#1]
I tried compiling the project with Xcode 7.3 and it is failing to find the framework headers.

    Users/duncan/src/mac/Disk-Inventory-X/Disk Inventory X 1.0 src/make/src/Disk Inventory X_Prefix.pch:7:13: fatal error: 'CocoaTechFoundation/NTFileDesc.h' file not found
    #import <CocoaTechFoundation/NTFileDesc.h>
            ^
    1 error generated.

**Comment by clawoo** [comment]
The frameworks were missing the symbolic links inside them. This is fixed now, thanks for reporting.
